# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'


target 'Get Short Usernames' do
pod 'AFNetworking', '~> 2.4'
end

target 'Get Short UsernamesTests' do

end

